# Generated by Django 3.0.1 on 2020-03-05 16:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('embeddedsite', '0002_auto_20200305_1200'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=600, verbose_name='Content')),
                ('cost', models.FloatField(blank=True, max_length=10)),
                ('currency', models.CharField(choices=[('NAIRA', '#'), ('US DOLLAR', '$'), ('POUNDS', 'P')], max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='author',
            name='about',
            field=models.TextField(verbose_name='About author'),
        ),
        migrations.AlterField(
            model_name='author',
            name='phone_number',
            field=models.CharField(max_length=14, verbose_name="Author's phone number"),
        ),
        migrations.AlterField(
            model_name='author',
            name='picture',
            field=models.FileField(upload_to='', verbose_name="Author's Picture"),
        ),
        migrations.AlterField(
            model_name='tutorial',
            name='video_link',
            field=models.URLField(max_length=50, verbose_name='Tutorial video link'),
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs'), ('ENGR', 'Engineer'), ('DR', 'Doctor'), ('PROF', 'Professor')], max_length=15)),
                ('about', models.TextField(verbose_name='About team member')),
                ('phone_number', models.CharField(max_length=14, verbose_name="Member's phone number")),
                ('position', models.CharField(choices=[('CEO', 'CEO'), ('AUTHOR', 'Author'), ('TUTOR', 'Tutor'), ('SELLS MANAGER', 'Sells manager'), ('DEVELOPER', 'Developer'), ('INTERN', 'Internship Student')], max_length=20, verbose_name='Position')),
                ('picture', models.FileField(upload_to='', verbose_name="Member's Picture")),
                ('twitter_handle', models.URLField(blank=True)),
                ('instagram_handle', models.URLField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Enquiry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600, verbose_name='Equiry body')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=2000, verbose_name='Your comment')),
                ('date_of_comment', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
        migrations.CreateModel(
            name='Circuit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField(max_length=600, verbose_name='Equiry message')),
                ('diagram', models.FileField(upload_to='', verbose_name='Circuit diagram')),
                ('designer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddedsite.Author')),
            ],
        ),
    ]
