# Generated by Django 3.0.1 on 2020-03-14 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('embeddedsite', '0011_comment_tutorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='tutorial',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='embeddedsite.Tutorial'),
        ),
    ]
