# Generated by Django 3.0.1 on 2020-03-15 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddedsite', '0012_auto_20200314_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='replied_to',
            field=models.IntegerField(default=-1),
        ),
    ]
