# Generated by Django 3.0.1 on 2020-03-05 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('embeddedsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('MR', 'Mr.'), ('MRS', 'Mrs'), ('ENGR', 'Engineer'), ('DR', 'Doctor'), ('PROF', 'Professor')], max_length=15)),
                ('picture', models.FileField(upload_to='', verbose_name="Tutor's Picture")),
                ('about', models.TextField(verbose_name='About Tutor')),
                ('phone_number', models.CharField(max_length=14, verbose_name="Tutor's phone number")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('description', models.TextField(max_length=2000, verbose_name='Content')),
                ('writeup', models.FileField(upload_to='', verbose_name='Project writeup')),
                ('cost', models.FloatField(verbose_name='Cost')),
                ('date_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Projectship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddedsite.Author')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddedsite.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('content', models.TextField(max_length=2000, verbose_name='Content')),
                ('video_link', models.URLField(max_length=50, verbose_name='Tutiral video link')),
                ('images', models.FileField(upload_to='', verbose_name='Tutorial images')),
                ('date_published', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutorship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddedsite.Author')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='embeddedsite.Tutorial')),
            ],
        ),
        migrations.RemoveField(
            model_name='tutors',
            name='user',
        ),
        migrations.RemoveField(
            model_name='tutorships',
            name='tutor',
        ),
        migrations.RemoveField(
            model_name='tutorships',
            name='tutorial',
        ),
        migrations.DeleteModel(
            name='Tutorials',
        ),
        migrations.DeleteModel(
            name='Tutors',
        ),
        migrations.DeleteModel(
            name='Tutorships',
        ),
        migrations.AddField(
            model_name='tutorial',
            name='tutor',
            field=models.ManyToManyField(through='embeddedsite.Tutorship', to='embeddedsite.Author', verbose_name='Tutor(s)'),
        ),
        migrations.AddField(
            model_name='project',
            name='author',
            field=models.ManyToManyField(through='embeddedsite.Projectship', to='embeddedsite.Author', verbose_name='Author'),
        ),
    ]
