# Generated by Django 3.0.1 on 2020-03-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddedsite', '0006_auto_20200307_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='images',
            field=models.FileField(default='images.png', upload_to='', verbose_name='Service images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.FileField(choices=[('F', models.FileField(default='image.png', upload_to='', verbose_name="Product's Picture"))], default='image.png', upload_to='', verbose_name="Product's Picture"),
        ),
    ]
