# Generated by Django 3.0.1 on 2020-03-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddedsite', '0009_auto_20200308_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorial',
            name='introduction',
            field=models.TextField(default='Introduction', max_length=200, verbose_name='Introduction'),
        ),
    ]
