# Generated by Django 3.0.1 on 2020-03-15 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddedsite', '0013_comment_replied_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='replied_to',
            field=models.IntegerField(default=0),
        ),
    ]
