# Generated by Django 3.1 on 2020-08-25 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('embeddedsite', '0014_auto_20200315_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='date',
            field=models.DateTimeField(verbose_name='Added on'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='replied_to',
            field=models.IntegerField(default=-1),
        ),
    ]
